grpc.services.customer.host=customer-service
grpc.services.customer.port=50051

grpc.retry.max-attempts=3
grpc.retry.delay-millis=100
grpc.retry.retryable-statuses=UNAVAILABLE,DEADLINE_EXCEEDED,RESOURCE_EXHAUSTED

# Interim non-Kubernetes example:
# grpc.services.customer.host=server-a
# grpc.services.customer.port=50051
