package com.example.grpc.simple;
import io.grpc.ManagedChannel; import io.grpc.ManagedChannelBuilder; import io.grpc.Status; import io.grpc.StatusRuntimeException;
import java.time.Duration; import java.util.Objects; import java.util.concurrent.ConcurrentHashMap; import java.util.concurrent.ConcurrentMap; import java.util.function.Function;
public final class GrpcClientManager implements AutoCloseable {
 private final ServiceEndpointProvider endpoints; private final int maxAttempts; private final Duration retryDelay; private final ConcurrentMap<String,GrpcClient> clients=new ConcurrentHashMap<>();
 public GrpcClientManager(ServiceEndpointProvider endpoints,int maxAttempts,Duration retryDelay){this.endpoints=Objects.requireNonNull(endpoints);if(maxAttempts<1)throw new IllegalArgumentException("maxAttempts must be >= 1");this.maxAttempts=maxAttempts;this.retryDelay=Objects.requireNonNull(retryDelay);if(retryDelay.isNegative())throw new IllegalArgumentException("retryDelay must not be negative");}
 public <T,R> R execute(String serviceName,GrpcClientFactory<T> factory,Function<T,R> operation){Objects.requireNonNull(factory);Objects.requireNonNull(operation);GrpcClient client=clientFor(serviceName,factory);for(int attempt=1;attempt<=maxAttempts;attempt++){try{return operation.apply(client.delegate());}catch(StatusRuntimeException e){if(!retryable(e)||attempt==maxAttempts)throw e;sleep();}}throw new IllegalStateException("Unreachable");}
 private <T> GrpcClient clientFor(String name,GrpcClientFactory<T> factory){if(name==null||name.isBlank())throw new IllegalArgumentException("serviceName must not be blank");GrpcClient existing=clients.get(name);if(existing!=null)return existing;ServiceEndpoint endpoint=endpoints.endpoint(name);ManagedChannel channel=ManagedChannelBuilder.forTarget(endpoint.target()).usePlaintext().build();GrpcClient created;try{created=new GrpcClient(endpoint,channel,factory.create(channel));}catch(RuntimeException e){channel.shutdownNow();throw e;}GrpcClient winner=clients.putIfAbsent(name,created);if(winner!=null){created.close();return winner;}return created;}
 private boolean retryable(StatusRuntimeException e){Status.Code c=e.getStatus().getCode();return c==Status.Code.UNAVAILABLE||c==Status.Code.DEADLINE_EXCEEDED||c==Status.Code.RESOURCE_EXHAUSTED;}
 private void sleep(){if(retryDelay.isZero())return;try{Thread.sleep(retryDelay.toMillis(),retryDelay.getNano()%1_000_000);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("Interrupted while waiting to retry gRPC call",e);}}
 public void close(){clients.values().forEach(GrpcClient::close);clients.clear();}
}